#!/usr/bin/env node

var fs = require('fs');
var https = require('https');
var constants = require('constants');
var config = JSON.parse(fs.readFileSync("config.json"));

// Just in case we move make multiple server and move them into a folder
var projectRoot = __dirname

var serverSuffix=""
var parentType="intermediate"

var isUsed = []
process.argv.forEach(function(v,i,a){
    isUsed.push(false)
})
for (var i = 0; i < process.argv.length; i++) {

    if (isUsed[i]){
        continue;

    } else if (i==0){
        isUsed[i]=true;
        continue;

    } else if (process.argv[i] === __filename ){
        isUsed[i] = true;
        continue;

    } else if (
        process.argv[i] === "--parent-type" &&
        process.argv.length >= i
    ) {
        parentType = process.argv[i+1];
        isUsed[i] = true;
        isUsed[i+1] = true;

    } else if (!isUsed[i]) {
        serverSuffix=process.argv[i];
        isUsed[i] = true;

    }
}



var serverName="server"+serverSuffix;
var serverFolder=projectRoot+"/server";

var serverKeyFile=[
    serverFolder,
    "private",
    serverName+".key.pem"
].join("/");

var serverCertFile=[
    serverFolder,
    "certs",
    serverName+".cert.pem"
].join("/");

var serverCertChainFile=[
    serverFolder,
    "certs",
    serverName+".chain.cert.pem"
].join("/");


// var serverCertChainList = [
//     fs.readFileSync(serverCertFile),
//     fs.readFileSync(projectRoot+"/"+config.intermediate.cert),
//     fs.readFileSync(projectRoot+"/"+config.master.cert)
// ]

var crlFile = "";
if(parentType="master"){
    crlFile = projectRoot + "/" + config.master.crl;
} else if(parentType="intermediate"){
    crlFile = projectRoot + "/" + config.intermediate.crl;
} else {
    throw Error("Parent type not valid");
}

// var options = {
//     key: fs.readFileSync(serverKeyFile),
//     cert: fs.readFileSync(serverCertFile),
//     ca: fs.readFileSync(serverCertChainFile),
//     crl: fs.readFileSync(crlFile),
//     passphrase:"",
//     requestCert: true,
//     rejectUnauthorized: true,
//     ciphers: [
//       "ECDHE-RSA-AES128-SHA256",
//       "DHE-RSA-AES128-SHA256",
//       "AES128-GCM-SHA256",
//       "!RC4",
//       "HIGH",
//       "!MD5",
//       "!aNULL"
//     ].join(":"),
//     honorCipherOrder: true,
//     secureProtocol: 'TLSv1_method'
// };


var options = {
    key: fs.readFileSync(serverKeyFile),
    cert: fs.readFileSync(serverCertFile),
    ca: fs.readFileSync(serverCertChainFile),
    crl: fs.readFileSync(crlFile),
    requestCert: true,
    rejectUnauthorized: true
};

https.globalAgent.options.ca = [];
if(parentType="master"){
    https.globalAgent.options.ca.push(fs.readFileSync(projectRoot+"/"+config.master.cert));
} else if(parentType="intermediate"){
    https.globalAgent.options.ca.push(fs.readFileSync(projectRoot+"/"+config.intermediate.chain));
} else {
    throw Error("Parent type not valid");
}


https.createServer(options, function (req, res) {
    if (req.socket.authorized){ // shouldn't even get here if not authorized
        console.log([
            new Date(),
            req.connection.remoteAddress,
            req.socket.getPeerCertificate().subject.CN
        ].join("\t"));
        res.writeHead(200);
        res.end("hello world\n");
    } else {
        console.log("Rejected");
        // console.log(req.socket.getPeerCertificate());
    }
}).listen(config.port);

console.log('listening on 0.0.0.0:'+config.port);
