#!/bin/bash
#
#
# This client connects to the local server running on port 1337.
# Should print 'hello world' and exit 0 on success
# On failure will print a curl error.
#
# Tested with the root->server->client model
# Untested with the root->intermediate->server->client model
#


parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
project_root=$(dirname "$parent_path")
previous_dir=$(pwd)

cd $project_root

help() {
  echo "USAGE: run.sh [--parent-type TYPE] [--name INDEX]"
  echo "TYPE (default: intermediate)"
  echo "INDEX (default: 1)"
  exit 0;
}

parent_type="intermediate"
client_index="1"

while [[ $# -gt 0 ]]; do
key="$1"
value="$2"
case $key in

    --debug)
      set -x
    ;;

    --parent-type)
      parent_type="$value"
      shift
    ;;

    --name)
      client_index="$value"
      shift
    ;;
    --help|-h)
      help
    ;;

esac
shift
done

source "scripts/load_vars.sh"

# domain=$(python -c "import json;print(json.loads(open(\"config.json\").read())[\"hostname\"])")
# port=$(python -c "import json;print(json.loads(open(\"config.json\").read())[\"port\"])")
# url="https://$domain:$port/"

url=$(cat config.json | jq -r "\"https://\(.hostname):\(.port)/\"")

curl --cacert "$parent_cert_chain" --cert "$client_cert:password" --key "$client_key" $url
