#!/usr/bin/python
import os
import sys
import json
import requests
import argparse

"""
Example Uses:

./client.py
./client.py 1
./client.py 1 --parent-type master
./client.py --parent-type master
./client.py --parent-type master 1
"""

project_root=os.path.dirname(os.path.abspath(os.path.dirname(__file__)))
os.chdir(project_root)

parser = argparse.ArgumentParser()

parser.add_argument(
    dest="client_suffix",
    default="",
)

parser.add_argument(
    "--parent-type",
    dest="parent_type",
    default="intermediate"
)

args = parser.parse_args()

client_name = "client"+ args.client_suffix

client_folder = os.path.join(
    project_root,
    "client"
)

client_key_file = os.path.join(
    client_folder,
    "private",
    "{client_name}.key.pem".format(client_name=client_name)
)

client_cert_file = os.path.join(
    client_folder,
    "certs",
    "{client_name}.cert.pem".format(client_name=client_name)
)

client_cert_chain_file = os.path.join(
    client_folder,
    "certs",
    "{client_name}.chain.cert.pem".format(client_name=client_name)
)

config = json.loads(open(os.path.join(project_root, "config.json")).read())

url = "{protocol}://{domain}:{port}/".format(
    protocol="https",
    domain=config["hostname"],
    port=config["port"],
)

r = requests.get(
    url,
    cert=(client_cert_file, client_key_file),
    verify=os.path.join(project_root, config[args.parent_type]["chain"]),
)

print(r)
